name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  foundry:
    uses: BreadchainCoop/etherform/.github/workflows/_foundry-cicd.yml@Rubydusa/upgrade-safety-validation
    permissions:
      contents: read
      pull-requests: write
    with:
      deploy-on-pr: true
      deploy-on-main: false
      deploy-script: "script/Deploy.sol:Deploy"
      run-slither: false
      run-upgrade-safety: true
      run-coverage: true
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      RPC_URL: ${{ secrets.RPC_URL }}

